export class DatabaseAs extends com.couchbase.lite.Database.As {}
export class Database extends com.couchbase.lite.Database {}
export class DatabaseConfiguration extends com.couchbase.lite.DatabaseConfiguration {}
export class Document extends com.couchbase.lite.Document {}
export class MutableDocument extends com.couchbase.lite.MutableDocument {}
export class DataSource extends com.couchbase.lite.DataSource {}
export class QueryBuilder extends com.couchbase.lite.QueryBuilder {}
export class Select extends com.couchbase.lite.Select {}
export class From extends com.couchbase.lite.From {}
export class Where extends com.couchbase.lite.Where {}
export class Dictionary extends com.couchbase.lite.Dictionary {}
export class MutableDictionary extends com.couchbase.lite.MutableDictionary {}
export class Result extends com.couchbase.lite.Result {}
export class ResultSet extends com.couchbase.lite.ResultSet {}
export class SelectResultFrom extends com.couchbase.lite.SelectResult.From {}
export class SelectResultAs extends com.couchbase.lite.SelectResult.As {}
export class SelectResult extends com.couchbase.lite.SelectResult {}
export class Expression extends com.couchbase.lite.Expression {}
export class PropertyExpression extends com.couchbase.lite.PropertyExpression {}